apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: journal
  template:
    metadata:
      labels:
        app: journal
    spec:
      containers:
        - name: journal
          image: docker.io/popelolole/journal-service:latest
          env:
            - name: DATABASE_URL
              value: jdbc:mysql://mysql-service:3306/journaldb

            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: journal-service-external
spec:
  selector:
    app: journal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: journal-service-internal
spec:
  selector:
    app: journal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
